version: '3.0'
services:
  ev-mongo:
    image: mongo
    container_name: "mongo"
    volumes:
      - ev-mongo:/data/db
    ports:
      - "27017"
    restart: always

  shiny-eevee-bot:
    container_name: "ev"
    build: .
    depends_on:
      - mongo
    environment:
      - PRINCESS_TRIXIE_TOKEN=${PRINCESS_TRIXIE_TOKEN}
    restart: always

volumes:
  ev-mongo: