version: '3.0'
services:
  ev-mongo:
    image: mongo
    container_name: "ev-mongo"
    volumes:
      - ev-mongo:/data/db
    ports:
      - "27017"
    networks:
      - ev-network
    restart: always

  shiny-eevee-bot:
    container_name: "ev"
    build: .
    depends_on:
      - ev-mongo
    environment:
      FOOBERRY_TOKEN: ${PRINCESS_TRIXIE_TOKEN}
      MONGO_URL: "mongodb://ev-mongo"
    networks:
      - ev-network
    restart: always

volumes:
  ev-mongo:

networks:
  ev-network: